### ISSUE TITLE
Configuração no contato, para não enviar mensagem em massa/campanha.

### ISSUE THREAD

**Issue by talsofa** [cleitonme/Whazing-SaaS#11]
No cadastro do contato, ter uma configuração, para não enviar mensagem de campanha, no caso não aparecer na lista, quando for adicionar os contatos na campanha, alguns clientes pedem para não receber mais mensagens, e seria mais pratico ter essa configuração no cadastro do contato

**Comment by cleitonme** [comment]
Adicionado recurso na versao 2.3.4
