### ISSUE TITLE
Quando o ticket for atendido, mudar a coluna visível para a abertos

### ISSUE THREAD

**Issue by talsofa** [cleitonme/Whazing-SaaS#12]
Hoje, quando inicia um atendimento, o ticket é aberto, mas a guia/coluna pendentes fica como selecionada, após iniciar o atendimento, mudar para a guia/coluna Abertos.

**Comment by cleitonme** [comment]
Tive analisando tem mudar vários pontos pouco resultado essa opção não foi imprementar, isso tudo feito no frontend se tiver interesse fazer e mandar boto disponível no repositório
