### ISSUE TITLE
anexe o nome do arquivo e sua respectiva extensão no chat

### ISSUE THREAD

**Issue by josenarvaez54** [cleitonme/Whazing-SaaS#15]
![image](https://github.com/user-attachments/assets/c49c9d38-514c-49b6-a45d-2a4419bc30cf)
O nome e a extensão do arquivo não são indicados na remessa.

![image](https://github.com/user-attachments/assets/2c760edb-ce04-44f4-add0-a3c83e4f2989)
Ao receber os arquivos, você pode ver o nome e o formato

**Comment by cleitonme** [comment]
falta detalhes nao tem como simular erro se nao to entendendo
