### ISSUE TITLE
bloquear contato

### ISSUE THREAD

**Issue by josenarvaez54** [cleitonme/Whazing-SaaS#17]
![image](https://github.com/user-attachments/assets/51684128-af2e-46a2-907a-4b5b8b485a0a)

Você pode integrar a opção de bloquear contato

**Comment by jeffersonlc94** [comment]
Você pode clicar em Editar contato tanto na tela de contatos quanto na tela de atendimento. Em seguida, basta marcar a opção **Ignorar contato** para bloquear futuras interações com esse contato.

**Comment by cleitonme** [comment]
Disponível ignora contato esta disponível  na ultima Versão 2.7.6.5
