### ISSUE TITLE
Mensagem de encerramento personalizada

### ISSUE THREAD

**Issue by ygorp** [cleitonme/Whazing-SaaS#19]
**Sua solicitação de recurso está relacionada a um problema? Descreva.**
Gostaria de uma seção para personalizar mensagens de encerramento, e quando fosse clicar em resolver o atendimento aparecece o menu dando opção de escolha de qual mensagem enviar.

**Descreva a solução que você gostaria**
Uma descrição clara e concisa do que você quer que aconteça.

**Descreva as alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você tenha considerado.

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by cleitonme** [comment]
liberado recurso na versao 2.5
