### ISSUE TITLE
Numa empresa a fatura aparece duplicada, como posso eliminar isso?

### ISSUE THREAD

**Issue by josenarvaez54** [cleitonme/Whazing-SaaS#22]
existem 2 empresas

![image](https://github.com/user-attachments/assets/cfc0476e-b43e-4b6f-9e0a-9f7583b180b1)

Numa empresa a fatura é duplicada

![image](https://github.com/user-attachments/assets/b1add1a0-3b57-4c60-81b3-a83f66dce207)

e na outra empresa não aparece nada

![image](https://github.com/user-attachments/assets/3c57a699-a720-4ab1-a91a-8091c552611c)

**Comment by cleitonme** [comment]
Falta detalhes para simular erro joga informações sem detalhes complicado, vencimento da empresa? Foi alterado plano? Data vencimento?

**Comment by cleitonme** [comment]
Somente pelo banco dados da de altera
