### ISSUE TITLE
Limite de tickets

### ISSUE THREAD

**Issue by talsofa** [cleitonme/Whazing-SaaS#24]
Hoje tem uma configuração que limita a quantidade de ticket carregado, solicito que essa configuração ignore os tickets que estão com o status de aberto, conforme chega novos tickets, ficando algum ticket em aberto mais antigo, ele acaba não aparecendo sem que pesquisamos pelo contato.

![image](https://github.com/user-attachments/assets/6ea33154-7a0f-49fe-bb89-9fb5a5a32aa7)

**Comment by cleitonme** [comment]
foi colocado na 2.3.5 configuração separada.. abertos/pedentes.. caso nao queira limitar coloque valor alto 9999
