### ISSUE TITLE
Configuração de tipografia da Aplicação

### ISSUE THREAD

**Issue by rohanbernartt** [cleitonme/Whazing-SaaS#26]
Minha contribuição seria uma sugestão para substituição dessa fonte "Josefin Sans", por uma fonte mais amigável em aplicações web, como por exemplo:  Inter, Poppins, Sora.

Ou habilitar uma configuração para que possamos setar uma fonte padrão para o projeto. Assim cada um escolhe a fonte do seu gosto.

![image](https://github.com/user-attachments/assets/69fbe8e5-24b0-4cb8-b106-b0ff2aef0144)

**Comment by cleitonme** [comment]
Poderia fazer testes fontes e avaliar pra mim qual tu acha melhor para fazer alteração por favor.. o

**Comment by rohanbernartt** [comment]
Farei os testes e envio aqui as sugestões :)
