### ISSUE TITLE
Opção de escolher outras cores para a Aplicação

### ISSUE THREAD

**Issue by rohanbernartt** [cleitonme/Whazing-SaaS#27]
Minha contribuição seria uma sugestão para criação de um local no painel de Configurações da Aplicação, para escolhermos pelo menos as cores primárias da aplicação (no print, trocar esse tom de azul/roxo para outra cor), para que seja possível combinar com a logo de cada projeto.

![image](https://github.com/user-attachments/assets/a9c836e9-a9ea-4b92-8529-1e2df3967155)

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
