### ISSUE TITLE
Visualizar conversas antigas com um contato

### ISSUE THREAD

**Issue by rohanbernartt** [cleitonme/Whazing-SaaS#28]
**Descreva o bug**
A cada mensagem que um contato manda é gerado um ticket. 
Porém não estou conseguindo visualizar o histórico da conversa, desse mesmo contato, dos outros tickets/fechados, no ticket novo. 

**Para reproduzir**
Gerar ticket, finalizar ticket, abrir novo ticket para a mesma pessoa.

**Comportamento esperado**
Seria interessante ser possivel visualizar todas as outras conversas com o contato.
O contato pode ter conversado outras vezes, com outros atendentes.

**Comment by cleitonme** [comment]
A cada mensagem que um contato manda é gerado um ticket.
isso faz parte do projeto e nao vai ser alterado, para poder separar setores e um setor nao acessar conversa do outro. para consultar coversas anteriores verificar tickets fechados... usar admin para acessar todos tickets caso sejam setores diferentes
