### ISSUE TITLE
Filtro por etiqueta

### ISSUE THREAD

**Issue by juniorsereno** [cleitonme/Whazing-SaaS#3]
Seria muito bom poder filtrar por etiqueta os atendimentos, principalmente para fazer follow-up com determinada etiqueta, simplificaria a busca e otimizaria o tempo.

**Comment by talsofa** [comment]
falando em etiqueta, seria interessante sincronizar com as do WhatsApp Busnnes

**Comment by Alex-HC2024** [comment]
Senão me engano já existe essa opção meu amigo
![image](https://github.com/user-attachments/assets/59b3fb0a-5da6-4094-ba21-e94c944707dc)

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
