### ISSUE TITLE
ticket retorna para pendente, outros usuários não podem visualizar

### ISSUE THREAD

**Issue by josenarvaez54** [cleitonme/Whazing-SaaS#30]
Quando o usuário não resolve e retorna o ticket para pendente, os demais usuários não conseguem visualizar aquele ticket que foi retornado. apenas o usuário que teve essa conversa pode ver

**Comment by cleitonme** [comment]
como falado jah anteriormete presciso de detalhes ta simular erro, prints paasso a passo... fica dificil assim analisar
