### ISSUE TITLE
Nivel de Usuario

### ISSUE THREAD

**Issue by VinnnyTNT** [cleitonme/Whazing-SaaS#32]
Possibilidade de ter mais um nível de usuário do tipo supervisor e esse supervisor conseguir atender todos os clientes vinculado a uma carteira mais não dando as opções de configuração da conta que o usuário administrador tem ?
(O nome supervisor seria só um exemplo)

Exemplo tem cliente que é atendimento por um vendedor mas ele tbm é atendimento pelo setor do sac e financeiro se o cliente tiver vinculado na carteira do vendedor o setor do financeiro tbm poderá chamar esse cliente

**Comment by cleitonme** [comment]
Da permissão do admin acessa todas conversas seria demais?

**Comment by cleitonme** [comment]
Ideia ótima mas tô perdido boa limites

**Comment by VinnnyTNT** [comment]
Não ia funcionar basicamente a ideia de ter nivel de usuario e para cada nivel de usuario ter alguns acessos que o outro não tem se deixar admin para esses demais usuarios eles terão acesso as configuração , com nivel de usuario limitamos os acessos e o usuario só vai ter acesso a carteira

**Comment by cleitonme** [comment]
somente carteira.. vou fazer diferente.. opção especial pra ela...

**Comment by cleitonme** [comment]
na versao 2.5 criei opção para ignorar carteira

**Comment by VinnnyTNT** [comment]
Perfeito fiz o testes e funcionou, muito obrigado
