### ISSUE TITLE
Botão Fechar ticket em massa

### ISSUE THREAD

**Issue by talsofa** [cleitonme/Whazing-SaaS#34]
Pensei em colocar o botão de fechar ticket em massa no dashbord, pq onde ele esta hoje, no painel de atendimento, ele demora muito pra liberar e começar a executar.
coloquei ele aqui na minha VPS de teste, só falta colocar os comandos, ainda não consegui localizar eles.
![image](https://github.com/user-attachments/assets/a6a2fd4d-694e-44cd-9c77-7a234f9e0cb2)

**Comment by cleitonme** [comment]
corrigido 2.7.3
