### ISSUE TITLE
Iniciando vários chatbots em apenas 1 ticket

### ISSUE THREAD

**Issue by pdl-clay** [cleitonme/Whazing-SaaS#35]
**Descreva o bug*
Quando estou usando o chatbot em grande escala e um dos clientes manda mais de uma mensagem como resposta a uma mensagem do chatbot o chatbot fala que vai tentar novamente e inicia um novo chatbot mesmo se o chatbot estiver no meio assim iniciando vários chat bots em apenas 1 ticket

**Para reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para cadastros
2. Clique em chat bot
3. Crie um novo 
4. Coloque mensagens de texto e alguns deleys entre as mensagens
5. Coloque ele para ser usado como chat bot principal
6. Mande uma mensagem de teste para o chat bot
7. Envie mais de uma mensagem 

**Comportamento esperado**
Iniciar vários chatbots no mesmo ticket

**Capturas de tela**

https://cdn.discordapp.com/attachments/1029917514945282169/1289976254442766346/IMG_5499.png?ex=66fac781&is=66f97601&hm=ac898bb13fe71bfef35759f89b0b639d0bad8ce8d5540337c7e029f47fc13c3f&

**Desktop (preencha as seguintes informações):**
- SO: [ubunto 20]
- Navegador [Chrome]
- Versão [20]
![IMG_5499](https://github.com/user-attachments/assets/dd4ed6fe-13b4-4e47-911e-68103e1002a8)
![734B40FF-B5C2-4F73-8140-933F037E0E07](https://github.com/user-attachments/assets/c62fb35c-ee9b-440d-ab33-809eded375cf)

**Comment by cleitonme** [comment]
baixe o chatbot para poder importar e avaliar se ta montado corretamente fluxo e simular erro, data.json

**Comment by cleitonme** [comment]
so fazer ajustes no fluxo
