### ISSUE TITLE
Habiliar e Desabilitar Campanhas

### ISSUE THREAD

**Issue by murielcaldas** [cleitonme/Whazing-SaaS#36]
Seria muito interessante se dentro do painel SAAS, onde é feito o cadastro dos planos, tovesse a opção de desabilitar as Camapanhas.
Dessa froma seria possivel, trabalhar planos com e sem envio de campanhas.

Aumentando assim a quantidade de planos que podem ser oferecidos ao cliente final.

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
