### ISSUE TITLE
Filtro na aba descrescente e crescente

### ISSUE THREAD

**Issue by mattpaiva** [cleitonme/Whazing-SaaS#37]
**Sua solicitação de recurso está relacionada a um problema? Descreva.**
Uma descrição clara e concisa do problema. Ex. Eu sempre fico frustrado quando [...]

**Descreva a solução que você gostaria**
Uma descrição clara e concisa do que você quer que aconteça.

**Descreva as alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você tenha considerado.

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by cleitonme** [comment]
Uma descrição clara e concisa

**Comment by mattpaiva** [comment]
na aba de aguardando, ter um botão que eu possa apertar descreste e crescente ou seja, eu apertando os últimos vão pra cima e se apertar novamente vão para baixo

**Comment by cleitonme** [comment]
Isso já tem
