### ISSUE TITLE
Tickets após 12 horas sem atividade desaparecem

### ISSUE THREAD

**Issue by josenarvaez54** [cleitonme/Whazing-SaaS#4]
Tickets de atendimento após 12 horas sem atividade desaparecem da lista ABERTO

**Comment by cleitonme** [comment]
Nos testes realizados verifiquei tem a ver quantidade te tickets e tempo que ta aberto vai ficando por ultimo, na versao 2.3.0 foi colocado opções para carregar mais tickets, e nas configurações quantidades tickets para carregar atendimento.
