### ISSUE TITLE
Opção de Ativar e Desativar em planos: N8N, TypeBot, Disparador

### ISSUE THREAD

**Issue by Elton-Coelho** [cleitonme/Whazing-SaaS#40]
Ter a Opção de Ativar e Desativar em planos: as integrações com 
N8N, TypeBot, Disparador

Para criar planos com as integrações!
E cobrar pela integração
para pagar o servidor adicional para N8N, TypeBot?

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
