### ISSUE TITLE
Configuração individual de quantidade de ticket por status

### ISSUE THREAD

**Issue by talsofa** [cleitonme/Whazing-SaaS#44]
Seria possível separar essa configuração de quantidade de tickets por status, abertos / pendentes, pois acontece muito quando envia campanha, ficar muita mensagem em pendente, e aberta nao aparecer.

![image](https://github.com/user-attachments/assets/5bf97973-1770-4403-aca0-46d71f89ee20)

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
