### ISSUE TITLE
Melhorias Kanban

### ISSUE THREAD

**Issue by edineifiorentini** [cleitonme/Whazing-SaaS#46]
Sugestões de melhorias Kanban
1 - Colocar a busca do contato dentro do Kanban, listas grande de contatos ficam difíceis de encontrar
2 - Adicionar etapa do kanban no atendimento
      - A Ideia é ter uma etiqueta mostrando o Kanban a qual está adicionado o cliente
![Captura de tela 2024-10-30 180148](https://github.com/user-attachments/assets/b774bbf8-4d7f-4173-a0fa-e7b0e1017b46)

      - Outra adição é selecionar o Kanban também na página de atendimento
![Captura de tela 2024-10-30 180142](https://github.com/user-attachments/assets/b7f2e17c-5083-48af-9bec-fa530ee57b0f)

**Comment by talsofa** [comment]
acho que no Kanban do Whaticket é assim, na etiqueta tem uma configuração pra marcar se é uma etapa do Kanban.

**Comment by edineifiorentini** [comment]
Sim, se tivesse a etapa do Kanban como etiqueta seria incrível

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
