### ISSUE TITLE
Mais de um atendente iniciar contato com o mesmo cliente

### ISSUE THREAD

**Issue by edineifiorentini** [cleitonme/Whazing-SaaS#48]
Seria interesse que mais de um atendente abra o chamado para um mesmo contato, no meu sistema ele tem bloqueado isso e se está nas configurações eu não consegui encontrar
![c1b58fc0-3946-4498-93a1-91a4fd41efdf](https://github.com/user-attachments/assets/37051c0a-13ca-4af9-8bde-824ddead6fa4)

**Comment by jeffersonlc94** [comment]
Se já houver um atendimento em andamento para o cliente, por exemplo, no WhatsApp 01, o sistema impedirá a abertura de uma nova conversa no mesmo canal. No entanto, se for em outro canal, como o WhatsApp 02, o sistema permitirá a abertura. Essa funcionalidade foi ajustada na _**versão 2.7.4-beta**_.

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
