### ISSUE TITLE
Histórico de mensagens

### ISSUE THREAD

**Issue by edineifiorentini** [cleitonme/Whazing-SaaS#49]
Seria interessante ter a seguinte função, imagine que um número foi banido, no celular se perde a mensagem, e no chat abre um novo chamado em branco, a ideia seria manter todo o histório com o cliente cadastrado naquele canal ou fila que ele já pertenceu.

Resumo, manter histórico mesmo após troca de número para um determinado usuário

**Comment by cleitonme** [comment]
mas so pegar ler qrcode denovo sem deletar conexao...
