### ISSUE TITLE
Editar mensagem enviada

### ISSUE THREAD

**Issue by VinnnyTNT** [cleitonme/Whazing-SaaS#50]
Gostaria de sugerir uma melhoria na interface de edição de mensagens. Seria interessante aumentar o tamanho do campo de edição, pois o quadro atual é bastante pequeno e, muitas vezes, as mensagens são longas. Isso dificulta a visualização e a correção das partes necessárias. Caso seja possível ampliar esse campo, facilitaria bastante 
![Captura de tela 2024-10-31 175518](https://github.com/user-attachments/assets/70bf702f-45dd-4ee6-9f8b-44cce3bf6261)

**Comment by cleitonme** [comment]
corrigido 2.7.3
