### ISSUE TITLE
Erro pré visualização de tickets pendentes

### ISSUE THREAD

**Issue by edineifiorentini** [cleitonme/Whazing-SaaS#51]
Alguns usuários não conseguem visualizar os tickets pendentes, mesmo habilitado nas opções a visualização não carrega para os usuários, já foi feito limpeza de cache, deslogar e relogar o usuário
![WhatsApp Image 2024-11-04 at 10 28 30](https://github.com/user-attachments/assets/4ee8a06d-1572-488e-9b41-7a5ed7236076)

**Comment by cleitonme** [comment]
corrigido 2.7.3
