### ISSUE TITLE
Erro ao enviar mensagem de bloqueio de ligação de voz e vídeo

### ISSUE THREAD

**Issue by fabianorosafotografia** [cleitonme/Whazing-SaaS#52]
**Descreva o bug**
Sistema está bloqueando as ligações, porém não notifica usuário.
*
![nao envia mensagem](https://github.com/user-attachments/assets/c28ade02-c6c0-449f-a639-d6cd1f534412)

**Comment by cleitonme** [comment]
![Screenshot_2024-11-07-17-43-14-233_com whatsapp w4b](https://github.com/user-attachments/assets/b37cf04a-301f-4525-9bcc-974c7deea9e3)


Olha aqui tá notificando normal
