### ISSUE TITLE
Error ao subir o backend

### ISSUE THREAD

**Issue by thigas88** [cleitonme/Whazing-SaaS#55]
Realizei toda a instalação em servidor linux Ubuntu 20.04, conforme mencionou no issue que abrir sobre o erro no frontend. O frontend subir e está buscando o backend via socket em localhost:3100.

Ao olhar o console está retornando falha de conexão. ao ver os logs do pm2 do serviço whazing-backend está aparecendo o seguinte erro:

![image](https://github.com/user-attachments/assets/8ff1bcea-59cf-443b-83dc-42f3df30306d)

**Comment by cleitonme** [comment]
Isso erro na instalação faltou módulos conforme tá no erro
