### ISSUE TITLE
Filtro de Contatos Por Fila

### ISSUE THREAD

**Issue by Alex-HC2024** [cleitonme/Whazing-SaaS#58]
Acredito que ajudaria muito organizar os contatos se tivesse a opção de separa-los por fila. Tipo separar os que estão no suporte, comercial, atendimento. Mais como uma forma de acrescentar uma organização.

**Comment by cleitonme** [comment]
Não ficou claro essa questão.. como já tem filtro fila tela atendimento estarei fechando
