### ISSUE TITLE
modo Campanha.

### ISSUE THREAD

**Issue by faeelcardoso123** [cleitonme/Whazing-SaaS#59]
Ultimamente após inciar varias campanhas , o sistema nao envia para todas as pessoas , assim a lista nunca finaliza.

quando vamos tentar excluir ele da o aviso de que nao dá para excluir por causa do status e que ela contem contatos pendentes de envio.

gostaria de saber se há como arrumar isso , pois minha tela ja esta lotada de campanhas e eu nao consigo apaga-las

**Comment by cleitonme** [comment]
Campanha algo complicado.. se tu importou planilha contatos não tem validação antes contato antes cadastra. Porque se consultar muitas vezes seguidas chance ban aumenta muito. Outra situação algo pesado se não for vps boa da problemas e mesmo vps boa algo sobrecarrega algo tem ser feito cuidado máximo 300 contatos de cada vez

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
