### ISSUE TITLE
erro ao criar, excluir e editar linhas

### ISSUE THREAD

**Issue by josenarvaez54** [cleitonme/Whazing-SaaS#60]
Ao criar, editar ou excluir uma linha, você deve forçar a atualização da página para poder ver as alterações que estão sendo feitas.

https://github.com/user-attachments/assets/a2798412-ea68-42c5-9a81-1e071e44354f

**Comment by cleitonme** [comment]
Estranho testei aqui não tá normal

**Comment by PauloBettin** [comment]
Aqui está assim também.

**Comment by cleitonme** [comment]
achei bug so afeta versao free, arrumei roda atualizacao, limpa cache, que vai resolver
