### ISSUE TITLE
Localizar conversa

### ISSUE THREAD

**Issue by pedro349** [cleitonme/Whazing-SaaS#61]
**Descreva a solução que você gostaria**
Uma maneira de pesquisar a conversa pelo número de whatsApp do cliente ou palavras chaves na conversa como por exemplo o CPF. 
Poderia ser tbm no painel de atendimento.

**Comment by cleitonme** [comment]
A busca texto na conversa ou número jah feito na aba atendimento.. painel de atendimento somente acompanhar por status não terá filtros extras

**Comment by cleitonme** [comment]
Disponível busca no atendimento na ultima Versão 2.7.6.5
