### ISSUE TITLE
Erro de ordenação de coluneas na tela de Contatos

### ISSUE THREAD

**Issue by Cristiangrando** [cleitonme/Whazing-SaaS#66]
**Descreva o bug**
Na tela de listagem de contatos, as colunas não batem com as descrições das mesmas. 
Carteira está em branco, mesmo sendo preenchida, Carteira está em etiquetas e assim por diante.

**Para reproduzir**
Etapas para reproduzir o comportamento:
1. Vá em Contatos
2. Veja na lista o ero

**Comportamento esperado**
Que cada dado estivesse na coluna correta.

**Capturas de tela**
![image](https://github.com/user-attachments/assets/dbbfadf7-e263-470e-a81d-3c40cb547a91)

**Desktop (preencha as seguintes informações):**
- SO: [por exemplo, iOS]
- Navegador [por exemplo, Chrome, Safari]
- Versão [por exemplo, 22]

**Smartphone (preencha as seguintes informações):**
- Dispositivo: [por exemplo, iPhone6]
- SO: [por exemplo, iOS8.1]
- Navegador [por exemplo, navegador de ações, Safari]
- Versão [por exemplo, 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by cleitonme** [comment]
Disponível esse recurso na ultima Versão 2.7.6.5
