### ISSUE TITLE
Problemas de Envio Duplicado e Reabertura de Tickets no Sistema

### ISSUE THREAD

**Issue by cadusantosofc** [cleitonme/Whazing-SaaS#71]
Estou enfrentando dois problemas importantes no sistema que precisam de atenção:

1. Envio duplicado de mensagens:

Quando um atendente aperta a tecla Enter mais de uma vez, o sistema envia a mesma mensagem repetidamente, em vez de uma única mensagem consolidada, como acontece no WhatsApp.
Exemplo:
Se o Enter for pressionado 2 vezes, a mesma mensagem é enviada 2 vezes.
Se o Enter for pressionado 10 vezes, a mensagem é enviada 10 vezes.
Esse comportamento gera confusão para os clientes e um volume desnecessário de mensagens na conversa.

2. Problemas com a importação de mensagens:

Durante a importação de mensagens, o sistema apresenta um comportamento inesperado, reabrindo tickets automaticamente várias vezes.
Esse processo gera notificações excessivas, criando desconforto para os atendentes e dificultando o acompanhamento eficiente dos tickets.
Esses problemas parecem estar presentes desde a época em que o sistema utilizava a base do Izing.
Segue abaixo um vídeo que demonstra claramente os erros mencionados.

https://i.imgur.com/fAWgqdo.mp4
https://i.imgur.com/fAWgqdo.mp4
https://i.imgur.com/fAWgqdo.mp4

**Comment by cleitonme** [comment]
logico ele vai reabrir tickets durante importação, espere acabar de importar para fechar o ticket..

**Comment by cadusantosofc** [comment]
O problema maior está sendo o erro de duplicar msg ocorrido pelo botão enter.
