### ISSUE TITLE
Botão Resolver no ticket

### ISSUE THREAD

**Issue by talsofa** [cleitonme/Whazing-SaaS#9]
Seria possível adicionar o  botão resolver, no itemticket, status, pendente e aberto, hoje tem essa função somente dentro do cabeçalho do ticket.
![Captura de tela 2024-09-03 224438](https://github.com/user-attachments/assets/95d54764-ad23-44df-a719-4e9555e236f8)

**Comment by cleitonme** [comment]
Adicionado recurso na versao 2.3.4
